const router = require('express').Router();
const { protect } = require('../middleware/auth');
const { register, login, getMe, logout, refreshToken, forgotPassword, resetPassword, sendOtp, verifyOtp } = require('../controllers/authController');
router.post('/register', register);
router.post('/login', login);
router.post('/send-otp', sendOtp);
router.post('/verify-otp', verifyOtp);
router.post('/refresh', refreshToken);
router.post('/forgot-password', forgotPassword);
router.post('/reset-password/:token', resetPassword);
router.get('/me', protect, getMe);
router.post('/logout', protect, logout);
module.exports = router;
