const nodemailer = require('nodemailer');

const createTransporter = () => nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: parseInt(process.env.SMTP_PORT) || 587,
  secure: process.env.SMTP_SECURE === 'true',
  auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS }
});

exports.sendEmail = async ({ to, subject, html, text }) => {
  try {
    const t = createTransporter();
    const info = await t.sendMail({
      from: `"${process.env.COMPANY_NAME || 'VendorBridge'}" <${process.env.SMTP_USER}>`,
      to, subject, html, text
    });
    return { success: true, messageId: info.messageId };
  } catch (error) {
    console.error('Email Error:', error.message);
    return { success: false, error: error.message };
  }
};

exports.sendInvoiceEmail = async ({ invoice, vendor, recipientEmail, message }) => {
  const html = `<!DOCTYPE html><html><head><style>
    body{font-family:Arial,sans-serif;background:#f5f5f5;margin:0;padding:20px}
    .container{background:#fff;max-width:600px;margin:0 auto;border-radius:8px;overflow:hidden}
    .header{background:#714b67;color:white;padding:30px;text-align:center}
    .body{padding:30px}
    table{width:100%;border-collapse:collapse;margin:16px 0}
    th{background:#714b67;color:white;padding:10px;text-align:left}
    td{padding:10px;border-bottom:1px solid #eee}
    .total{font-weight:bold;font-size:20px;color:#714b67;text-align:center;padding:20px}
    .footer{background:#f9f9f9;padding:16px;text-align:center;color:#888;font-size:12px}
  </style></head><body>
  <div class="container">
    <div class="header"><h2>Invoice #${invoice.invoiceNumber}</h2><p>${vendor?.name || 'Vendor'}</p></div>
    <div class="body">
      ${message ? `<p>${message}</p>` : ''}
      <table><thead><tr><th>Item</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr></thead>
      <tbody>${invoice.items.map(i => `<tr><td>${i.name}</td><td>${i.quantity}</td><td>₹${(i.unitPrice||0).toLocaleString('en-IN')}</td><td>₹${(i.total||0).toLocaleString('en-IN')}</td></tr>`).join('')}</tbody>
      <tfoot>
        <tr><td colspan="3" style="text-align:right"><strong>Subtotal:</strong></td><td>₹${(invoice.subTotal||0).toLocaleString('en-IN')}</td></tr>
        <tr><td colspan="3" style="text-align:right"><strong>GST (${invoice.taxRate}%):</strong></td><td>₹${(invoice.taxAmount||0).toLocaleString('en-IN')}</td></tr>
        <tr><td colspan="3" style="text-align:right"><strong>Grand Total:</strong></td><td style="color:#714b67;font-weight:bold">₹${(invoice.grandTotal||0).toLocaleString('en-IN')}</td></tr>
      </tfoot></table>
      <div class="total">Total Due: ₹${(invoice.grandTotal||0).toLocaleString('en-IN')}</div>
    </div>
    <div class="footer">Auto-generated by VendorBridge ERP</div>
  </div></body></html>`;
  
  return exports.sendEmail({ to: recipientEmail, subject: `Invoice ${invoice.invoiceNumber} - ₹${(invoice.grandTotal||0).toLocaleString('en-IN')}`, html });
};

exports.sendPasswordResetEmail = async ({ email, resetUrl, name }) => {
  const html = `<!DOCTYPE html><html><body style="font-family:Arial,sans-serif;background:#f5f5f5;padding:20px">
  <div style="background:white;max-width:500px;margin:0 auto;border-radius:8px;overflow:hidden">
    <div style="background:#714b67;color:white;padding:30px;text-align:center"><h2>Password Reset</h2></div>
    <div style="padding:30px">
      <p>Hi ${name},</p>
      <p>Click the button below to reset your VendorBridge password. This link expires in 10 minutes.</p>
      <div style="text-align:center;margin:24px 0">
        <a href="${resetUrl}" style="background:#714b67;color:white;padding:14px 28px;text-decoration:none;border-radius:6px;font-weight:bold">Reset Password</a>
      </div>
      <p style="color:#888;font-size:12px">If you did not request this, please ignore this email.</p>
    </div>
  </div></body></html>`;
  return exports.sendEmail({ to: email, subject: 'VendorBridge - Password Reset', html });
};

exports.sendOtpEmail = async ({ email, otp, name }) => {
  const html = `<!DOCTYPE html><html><body style="font-family:Arial,sans-serif;background:#f5f5f5;padding:20px">
  <div style="background:white;max-width:500px;margin:0 auto;border-radius:8px;overflow:hidden">
    <div style="background:#714b67;color:white;padding:30px;text-align:center"><h2>Login OTP</h2></div>
    <div style="padding:30px">
      <p>Hi ${name || 'User'},</p>
      <p>Your One-Time Password (OTP) to login to VendorBridge is:</p>
      <div style="text-align:center;margin:24px 0;font-size:32px;font-weight:bold;letter-spacing:4px;color:#714b67;">
        ${otp}
      </div>
      <p>This code expires in 5 minutes. Do not share it with anyone.</p>
    </div>
  </div></body></html>`;
  return exports.sendEmail({ to: email, subject: 'VendorBridge - Login OTP', html });
};
